### ISSUE TITLE
Can't access repository

### ISSUE THREAD

**Issue by jatkins23** [lucified/lucify-refugees#3]
Hi, this project is awesome. I'm working on something similar and was very intrigued to look into how you all went about this and maybe use some of your code. However, in following the instructions on your github, I was unable to figure out how to do so. It seems the issue is coming from an inability to access a git repository on gitlab but I'm not sure as I don't have a ton of experience with this. Any help would be much appreciated as I am coming up on a deadline for submitting my project. Thank you very much, find attached a screenshot of my terminal output while attempting to run npm install.

<img width="1280" alt="screen shot 2015-11-28 at 12 47 04 am" src="https://cloud.githubusercontent.com/assets/10275262/11450313/901776d8-9569-11e5-963b-1cadb37c1766.png">

**Comment by juhoojala** [comment]
Hi, cool to hear that you are trying the project out!

The problem seems to be with us using `git+ssh` instead of `git+https` in package.json to refer to those packages hosted in GitLab. While the repositories are public, you will need to have a GitLab account with a public key configured to download them.

Unfortunately we are a right now really busy with an other project, so we don't have time to fix those refs. Meanwhile you can create a GitLab account and configure an SSH key. That probably fixes the issue.

**Comment by jatkins23** [comment]
Thank you very much for the speedy reply. That fixed much of the issues and I was almost able to install everything however it errored out on "contextify@0.1.15 install: `node-gyp rebuild`". I'm sure there is some easy fix for this but I couldn't find anything online other than telling me to update node, which I have done. Again, any advice would be much appreciated. Thank you!

Jon

Again attached is my terminal output:
<img width="1280" alt="screen shot 2015-11-28 at 11 16 05 am" src="https://cloud.githubusercontent.com/assets/10275262/11452805/e1cb47ae-95c1-11e5-92fa-e15b52cb236c.png">

**Comment by juhoojala** [comment]
Hi,

I don't immediately know what the problem is. We have been developing this with fairly old versions of node, specifically `v.12.0` and `v.12.6`

You could try installing node version manager and switching to the old node version:
http://michael-kuehnel.de/node.js/2015/09/08/using-vm-to-switch-node-versions.html

-Juho

**Comment by jatkins23** [comment]
I have still been unable to get it to work. Have tried switching to both 12.0 and 12.6, as well as installing node-gyp itself (however, from the google searching I've done, it should be included in any node 12.0 or above). I reinstalled node, reinstalled command-line developer tools thru Xcode and re-cloned the repository. I also tried downloading all of the dependencies from your Gitlab and changing the links to the local addresses. I'm kinda stuck haha. If you have any other ideas or figure it out, any advice would be much appreciated, thank you!
